import assert from 'node:assert/strict';
import fs from 'node:fs';
import { catalogue, pricePackage, wardFeatures } from '../src/billing/package-pricing.js';
import { checkoutLines } from '../dist/billing/checkout.js';
import { reconcileFeatures } from '../dist/billing/reconcile.js';
import { config } from '../dist/config.js';
const ward = (name='Ward 1',modules=[],plan='essential') => ({name,site:'Main site',plan,modules});
const selection = (wards=[ward()],tablets=0,interval='monthly',enterprise=false) => ({wards,tablets,interval,enterprise});
assert.equal(pricePackage(selection([ward('A',['rostering'])],1)).gross,27079);
assert.equal(pricePackage(selection([ward('A',['rostering']),ward('B')],2)).gross,48758);
assert.equal(pricePackage(selection([ward('A',[], 'professional'),ward('B')])).gross,53760);
const four=catalogue.modules.slice(0,4).map(module=>module.id);
assert.equal(pricePackage(selection([ward('A',four)])).savings[0].monthly,3000);
assert.equal(pricePackage(selection([ward('A',four,'professional')])).lines.length,1);
assert.equal(pricePackage(selection([ward('A',four,'professional')])).selection.wards[0].modules.length,0);
assert.equal(pricePackage(selection([ward('A'),ward('B')],0,'monthly',true)).lines[0].quantity,1);
assert.equal(pricePackage(selection([ward()],0,'yearly')).gross,178800);
assert.throws(()=>pricePackage(selection([ward('A',['rostering'])],0,'yearly')));
assert.throws(()=>pricePackage(selection([ward()],1,'yearly')));
assert.throws(()=>pricePackage(selection([ward('A',['unknown'])])));
assert.throws(()=>pricePackage(selection([ward('A',['rostering','rostering'])])));
assert.throws(()=>pricePackage(selection([ward(),ward()])));
assert.throws(()=>pricePackage(selection([ward()],-1)));
assert.throws(()=>pricePackage(selection([ward()],1.5)));
const tax=pricePackage(selection([ward()],3));
assert.equal(tax.gross,17880+3*3799);
assert.equal(tax.net+tax.vat,tax.gross);
assert.equal(wardFeatures(ward('A',['rostering']),false).rostering,true);
assert.equal(wardFeatures(ward('B'),false).rostering,false);
assert.equal(fs.readFileSync(new URL('../../website/package-pricing.js',import.meta.url),'utf8'),fs.readFileSync(new URL('../src/billing/package-pricing.js',import.meta.url),'utf8'));
console.log('PASS: VAT, tablet gross price, mixed wards, included modules, upgrade saving, annual rules, validation and matching website catalogue');
config.stripePriceIds.essential.monthly='price_essential';
config.stripeExtraPriceIds.rostering='price_roster';
config.stripeExtraPriceIds.tablets='price_tablet';
const prices={price_essential:{active:true,currency:'gbp',unit_amount:14900,tax_behavior:'exclusive'},price_roster:{active:true,currency:'gbp',unit_amount:4500,tax_behavior:'exclusive'},price_tablet:{active:true,currency:'gbp',unit_amount:3799,tax_behavior:'inclusive'}};
const client={prices:{retrieve:async id=>({...prices[id],recurring:{interval:'month',interval_count:1,usage_type:'licensed'}})}};
const cart=selection([ward('A',['rostering']),ward('B')],2);
const result=await checkoutLines(client,cart);
assert.deepEqual(result.lineItems,[{price:'price_essential',quantity:2},{price:'price_roster',quantity:1},{price:'price_tablet',quantity:2}]);
prices.price_tablet.tax_behavior='exclusive';
await assert.rejects(()=>checkoutLines(client,cart));
prices.price_tablet.tax_behavior='inclusive';
prices.price_roster.unit_amount=6900;
await assert.rejects(()=>checkoutLines(client,cart));
console.log('PASS: one set of subscription lines; reject mismatched Stripe prices and VAT behaviour before checkout');
const ordered=result.lineItems.map((item,index)=>({...item,key:result.quote.lines[index].key}));
const actual=result.lineItems;
let reconciled=reconcileFeatures(cart,ordered,actual);
assert.equal(reconciled.reviewRequired,false);assert.equal(reconciled.features[0].rostering,true);assert.equal(reconciled.features[1].rostering,false);
reconciled=reconcileFeatures(cart,ordered,actual.map(item=>item.price==='price_tablet'?{...item,quantity:3}:item));
assert.equal(reconciled.reviewRequired,true);assert.equal(reconciled.features[0].rostering,true);
reconciled=reconcileFeatures(cart,ordered,actual.filter(item=>item.price!=='price_roster'));
assert.equal(reconciled.features[0].rostering,false);
console.log('PASS: purchased features remain ward-specific; tablet changes preserve software; removed modules are withdrawn');
