const api='https://adequate-energy-production.up.railway.app/api';
const $=id=>document.getElementById(id);let token;let busy=false;
async function call(path,body){const r=await fetch(api+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Request failed');return result;}
async function action(fn){if(busy)return;busy=true;$('message').textContent='';document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function el(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n;}
async function load(){const {orders}=await call('/show/admin/orders');$('login').hidden=true;$('admin').hidden=false;$('orders').replaceChildren();if(!orders.length)$('orders').append(el('p','No show orders yet.'));
for(const order of orders){const card=el('section');card.className='builder-panel show-order';card.append(el('h2',order.organisationName),el('p',`${order.contactName} · ${order.contactRole} · ${order.email} · ${order.phone}`),el('p',`Reference: ${order.id}`),el('p',`${order.package.wards.length} ward(s) · £${(order.quote.software.gross/100).toFixed(2)} ${order.package.interval} software · ${order.package.tablets} tablets`),el('p',`Payment method: ${order.paymentReady?'saved':'pending'} · Activation: ${order.proposedDate||'not proposed'} · ${order.scheduled?'scheduled':order.confirmedAt?'confirmation received — scheduling pending':'awaiting confirmation'} · ${order.billingStatus||'not active'}`));
if(!order.confirmedAt){const form=el('form');const label=el('label','Proposed activation date');const date=el('input');date.type='date';date.required=true;date.value=order.proposedDate||'';label.append(date);const submit=el('button','Propose date');submit.className='checkout-button';form.append(label,submit);form.addEventListener('submit',e=>{e.preventDefault();action(async()=>{await call('/show/admin/propose',{id:order.id,date:date.value});await load();});});card.append(form);}
if(order.scheduled&&order.package.tablets&&!order.tabletReturned){const returned=el('button','Confirm all tablets returned and stop hire');returned.className='outline-button';returned.addEventListener('click',()=>{if(window.confirm('Have ALL tablets for this order been returned? This stops their future hire charges.'))action(async()=>{await call('/show/admin/tablets-returned',{id:order.id,allReturned:true});await load();});});card.append(returned);} $('orders').append(card);}}
$('admin-login').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const data=Object.fromEntries(new FormData(e.target));if(!data.organisationId)delete data.organisationId;const r=await call('/staff/pin-login',data);if(r.staff.role!=='super_admin')throw new Error('A super-admin account is required.');token=r.session.token;e.target.reset();await load();});});
$('refresh').addEventListener('click',()=>action(load));$('logout').addEventListener('click',()=>{token=null;$('admin').hidden=true;$('orders').replaceChildren();$('login').hidden=false;});
